services:
  backend:
    build:
      context: ./apps/backend
      target: dev

    volumes:
      - ./apps/backend/src:/app/src

    env_file:
      - path: ./apps/backend/.env.example
        required: true
      - path: ./apps/backend/.env
        required: false

    healthcheck:
      test: ["CMD", "curl http://localhost:3000/healthcheck"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 5s
    
    depends_on:
      db:
        condition: service_healthy

  ### ----- DATABASE ----- ###
  db:
    image: postgres:18-alpine

    volumes:
      - db-data:/var/lib/postgresql

    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'iam'

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d iam"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 20s

volumes:
  db-data:
